CREATE TABLE IF NOT EXISTS visitor(id INTEGER PRIMARY KEY AUTOINCREMENT,names TEXT,prcid TEXT,mobilenumber TEXT,emailadd TEXT,wavelia TEXT,useragree TEXT,img TEXT);
INSERT or IGNORE INTO visitor VALUES (1,'VILLANUEVA, KIERLEY','113197', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (2,'QUILAO-VILLANUEVA, ELAH','113419', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (3,'GARCIA, CHERRY','113656', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (4,'CALIZO,JOHN JAGGER','95692', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (5,'CORACHEA, DENNIS','112538', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (6,'UYCOQUE, EDUARDO','62882', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (7,'MANALO, MARY ANN','112484', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (8,'MAMARIL, CLEA','110720', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (9,'TORRES, ALICE ODETTE','119906', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (10,'MADERAZO, AUREA','60232', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (11,'FLORES, BIBIANA','85344', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (11,'DONATO, ARLENE','57958', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (13,'CHAVEZ, ROSALINDA','59905', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (14,'JALUAGUE, ANNA LIZA','113945', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (15,'BONIFACIO, ELNATH','139151', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (16,'ATIENZA, BENITO','72893', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (17,'ARANAS, ARISTOTLE','100036', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (18,'ALDAY, KAREN','105539', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (19,'ADARLO, MELINDA','80220', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (20,'ORTIZ, FE','108152', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (21,'SUMANG, LINA','87841', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (22,'MANALO, JENNIFER','97375', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (23,'ROXAS, CHRISTIAN ALLEN','106657', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (24,'VIVAS, BELINDA','85033', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (25,'MAGSINO, MEILEEN','86632', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (26,'ILLARUZ, MARIA LEONORA','78955', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (27,'DOMINGO, MA. PERPETUA','80030', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (28,'MARQUINO, GLENDA','69755', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (29,'MACABABBA, EVELITA','63621', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (30,'MANALO, ROSALINDA','59147', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (31,'NOCHE-ESMENDE, CLARISSA','99771', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (32,'CRESENCIA, CYNTHIA','73860', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (33,'CRUZ, BENITO','82789', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (34,'ABJELINA, CECILIA','68710', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (35,'MERCADO, MA JOYCELYN','68569', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (36,'ABARINTOS-PRING, ADELINA','76861', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (37,'VILLAVIRAY, BELINA','59655', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (38,'SABALVORO-ORIONDO, CHRISTINA MARIE','79486', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (39,'VALLES, MARY JANE','93269', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (40,'MALVEDA, AGNES','108206', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (41,'BATHAN, LILIAN','66290', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (42,'SANTIAGO, NORIE','91350', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (43,'SINGH, SUSAN','562772', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (44,'REYES, AILEEN ','111481', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (45,'LIPAT, LUZVIMINDA','75110', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (46,'BRIONES-ARETA, MARIETTA','74235', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (47,'DY, HELEN','67123','', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (48,'RELLORA, AMELIA','58037', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (49,'SY, SONIA','94702','', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (50,'MORCILLA, JOY','118018', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (51,'LUSTRE, MARITESS','111415', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (52,'LAT-FABROS, BABY JANE','114476', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (53,'CASTILLO, JEANETTE','109294', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (54,'GUEVARRA, MA. LYRA','114576', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (55,'MACATANGAY, BEN VENUS','91087', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (56,'ATIENZA, ARIEL','83425','', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (57,'LOPO, YEENAH','109779','', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (58,'BLANDO, MA REGINA','85122', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (59,'SAPLAN, LORETA','74518', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (60,'VIDAL, EDRALIN','87851', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (61,'UMANDAL, MARITES','76635', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (62,'BESING, ELIZABETH','96838', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (63,'LAT, ERNESTO','58147', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (64,'SILVA, REDEN','84360', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (65,'MAGSINO, JOSEPHINE','54600', '', '', '', '0', '');
INSERT or IGNORE INTO visitor VALUES (66,'MACASAET, RODERICK','99638', '', '', '', '0', '');